-- https://lean-lang.org/functional_programming_in_lean//Monads/The-IO-Monad/#Functional-Programming-in-Lean--Monads--The-IO-Monad
#print Nat
#print Char.isAlpha
#print List.isEmpty
#print IO
#print IO.Error
#print EIO
#print EStateM
#print EStateM.Result
#print EStateM.pure
#print EStateM.bind
#print IO.RealWorld